### PR TITLE
Tiles and markers for Towns & Towers

### PR DESCRIPTION
**Pull request by murphy-slaw**
This adds tiles and markers for all of the normal (non-"exclusive") village types in the Towns & Towers mod/datapack, and also for the Desert Temple Mimic structure.

desert_mimic
grove_outpost
jungle_village

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
I think the existing tile-based setup for outposts should work better for the outposts variants in this mod - have you tried that out?

**Comment by murphy-slaw** [comment]
I was planning to use tiles for the pillager structures that follow the "tower and a few outbuildings" style of vanilla pillager outposts,but there are a few "camps" that are just collections of tents, and I thought that those might be better off as markers because the tent tiles would get lost against the background.

**Comment by sleepingdragoninn** [comment]
the marker / tile distinction mostly comes down to places you need to revisit often (villages, end city) or places that look bad as tiles (monuments, mansions) - if you absolutely need a marker, I'd say see if you can't jerry-rig a more unique marker texture by manually white-outlining the existing tent texture - otherwise it's confusing differentiating it from places with villagers

**Comment by murphy-slaw** [comment]
That makes sense. It occurs to me that the start jigsaw for each of the tent camps is a campfire circle, so maybe I will add a tile for that to make the camps more distinct.

**Comment by murphy-slaw** [comment]
Added tiles for the pillager structures. For now I'm using the plains meeting point for campfires because I wasn't able to come up with a campfire tile I was happy with. All of the non-camp structures are single buildings so I used the watchtower tile for them.

Camp:
wooded_badlands_camp
Fort:
desert_fort

**Review by sleepingdragoninn — APPROVED** [review]
looks good!

**Comment by sleepingdragoninn** [comment]
ah hold on, we did add a bit of structure priority to builtin villages last night - did you want time to copy that?

**Comment by murphy-slaw** [comment]
Yeah, let me copy the priority changes and then we can close this out.

**Comment by murphy-slaw** [comment]
Okay, village structures have priorities set like vanilla now.

**Comment by sleepingdragoninn** [comment]
great! I'll merge this in

**Pull request merged**
